GET http://localhost:5213/games

###
GET http://localhost:5213/game/3


###
POST http://localhost:5213/games
Content-Type: application/json

{
    "name": "MineCraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}